### ISSUE TITLE
How do I properly share cloud bucket secrets with my python script

### ISSUE THREAD

**Issue by jbusecke** [jbusecke/cmip6_derived_cloud_datasets#5]
What is the preferred way to 'pipe' key/secret values stored as github secrets into a python script?

Here are a few ways I thought about:
1) Define an environmental variable at github action runtime, and query that from within the script with `os.environ[...]`
2) Make a command line input for the secrets and calling the script with `python script.py --key${{secrets.....}} --secret=${{}}`

Are there other less clunky ways to do this? And does one of these methods have security implications?

**Comment by rabernat** [comment]
✅  1. Define an environmental variable at github action runtime, and query that from within the script with `os.environ[...]`

**Comment by jbusecke** [comment]
Thanks. I implemented that [here](https://github.com/jbusecke/cmip6_derived_cloud_datasets/pull/6). Works like a charm!
